# Generated by Django 3.1.4 on 2021-08-08 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0002_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
