# Generated by Django 3.1.4 on 2021-08-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0004_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
