# Generated by Django 3.1.4 on 2021-08-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0007_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
