# Generated by Django 3.1.4 on 2021-08-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0008_delete_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
