# Generated by Django 3.1.4 on 2021-08-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0010_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
