# Generated by Django 3.1.4 on 2021-08-25 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0012_session_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='expiry_date',
            new_name='creation_date',
        ),
    ]
